import Head from 'next/head';
import Footer from '../components/Footer.jsx';
import Header from '../components/header.jsx';
import Nav from '../components/Nav.jsx';
import Results from '../components/Results.jsx';
import requests from '../utils/requests.js';

export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Header />
      <Nav />
      <Results results={results} />
      <Footer />
    </>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then(res => res.json());

  return {
    props: {
      results: request.results,
    }
  }
};